spring.application.name=cascaron

# Puerto de la app
server.port=8080

#DB local 
spring.datasource.url=jdbc:postgresql://localhost:5432/cascaron
spring.datasource.username=postgres
spring.datasource.password=12345


spring.jpa.show-sql=true

# Opcional: Dialecto de Hibernate para PostgreSQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

# Opcional: Configuraciones adicionales de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

#Limitar la documentacion de APIs, para el package 'controller'
springdoc.packages-to-scan=com.example.cascaron.controller

#Swagger 
springdoc.swagger-ui.theme=dark

spring.jackson.time-zone=America/Mexico_City
